server:
  port: 9098
spring:  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:currencymsDb;DB_CLOSE_DELAY=-1
    username: sa
    password:     
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"        

       
